// ===== 配置常量 =====
const CONFIG = {
    SCALE_FACTOR: 5,
    MAX_MAGNITUDE: 10000,
    MIN_MAGNITUDE: 1,
    MAX_ANGLE: 360,
    MIN_ANGLE: 0,
    DEFAULT_MAGNITUDE: 20,
    DEFAULT_ANGLE: 0,
    DEFAULT_LINE_WIDTH: 2,
    ARROWHEAD_LENGTH: 10,
    TICK_SPACING: 20,
    BACKGROUND_SPACING: 20,
    HISTORY_LIMIT: 50,
    CONTROL_POINT_DISTANCE: 30,
    TOUCH_TARGET_SIZE: 20
};