// ===== 应用状态 =====
const state = {
    forces: [],
    nextForceId: 1,
    nextForceNumber: 1,
    defaultMagnitude: CONFIG.DEFAULT_MAGNITUDE,
    defaultAngle: CONFIG.DEFAULT_ANGLE,
    selectedForce: null,
    isDragging: false,
    dragStartX: 0,
    dragStartY: 0,
    viewScale: 1,
    viewOffsetX: 0,
    viewOffsetY: 0,
    isResizing: false,
    resultantForce: null,
    showResultant: true,
    fixedColor: false,
    lineWidth: CONFIG.DEFAULT_LINE_WIDTH,
    backgroundType: "none",
    resultantColor: "#d13438",
    draggingControlPoint: null,
    history: [],
    historyIndex: -1,
    touchStartDistance: 0,
    touchStartScale: 1,
    isPinching: false,
    dragStartMagnitude: 0,
    dragStartAngle: 0
};